
image:
  repository: rocketpool/smartnode
  tag: v0.0.3
  pullPolicy: IfNotPresent

storageAddress: 0xbbCbc87447fE120E1Bc73dBd11bc4Dc1086FFa25

datadir: /.rocketpool

eth1:
  provider: http://eth1:8545
  proxy: true
  infuraId: changeme

eth2:
  provider: http://eth2:8545

storage:
  capacity: 1Gi

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 200m
    memory: 512Mi

ports:
  metrics: 5052

# Currently only Lighthouse + Infura is supported

validator:
  image:
    repository: sigp/lighthouse
    tag: v0.2.13
    pullPolicy: IfNotPresent

  debugLevel: info
  testnet: medalla
  graffiti: Lighthouse Validator
