
image:
  repository: rocketpool/smartnode
  tag: v0.0.8
  pullPolicy: IfNotPresent

storageAddress: 0xA85A8022E8F28E49B8BBfb792f93ee914B342C3b

# has to be this right now
datadir: /.rocketpool

eth1:
  provider: http://eth1:8545
  proxy: true
  infuraId: changeme

eth2:
  # pick one or the other and set the provider accordingly
  lighthouse: true
  prysm: false
  # specify without "http://" because Prysm doesn't use http
  provider: eth2:8545

storage:
  capacity: 1Gi

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 200m
    memory: 512Mi

ports:
  metrics: 5052

cli:
  image:
    repository: eskp/rocketpool-cli
    tag: stable
    pullPolicy: IfNotPresent

  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 100m
      memory: 256Mi

proxy:
  image:
    repository: rocketpool/smartnode
    tag: v0.0.3
    pullPolicy: IfNotPresent


lighthouse:
  image:
    repository: sigp/lighthouse
    tag: stable
    pullPolicy: IfNotPresent

  debugLevel: info
  network: pyrmont
  graffiti: rocket-pool

  ports:
    metrics: 5064


prysm:
  image:
    repository: gcr.io/prysmaticlabs/prysm/validator
    tag: stable
    pullPolicy: IfNotPresent

  verbosity: info
  graffiti: rocket-pool

  ports:
    metrics: 8081