image:
  repository: rocketpool/smartnode
  tag: v1.0.0-beta.2
  pullPolicy: IfNotPresent

storageAddress: 0xDeE7ec57E6b9f7F9A27e68821F3763e9d2537096
rplFaucetAddress: 0x6aC372F4bd37b9588D7eAb93A67E304421E26E48

# has to be this right now
datadir: /.rocketpool

eth1:
  provider: http://eth1:8545
  wsProvider: ws://eth1:8546
  infuraId: changeme

eth2:
  # pick one or the other and set the provider accordingly
  lighthouse: false
  prysm: false
  # specify without "http://" because Prysm doesn't use http
  provider: eth2:8545

storage:
  capacity: 1Gi

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 200m
    memory: 512Mi

ports:
  metrics: 5052

metrics:
  enabled: false
  image:
    repository: eskp/rocketpool-metrics
    tag: latest
    pullPolicy: IfNotPresent

  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 300m
      memory: 512Mi

cli:
  image:
    repository: eskp/rocketpool-cli
    tag: stable
    pullPolicy: IfNotPresent

  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 100m
      memory: 256Mi

proxy:
  enabled: false
  image:
    repository: rocketpool/smartnode
    tag: v0.0.3
    pullPolicy: IfNotPresent


lighthouse:
  image:
    repository: sigp/lighthouse
    tag: stable
    pullPolicy: IfNotPresent

  debugLevel: info
  network: pyrmont
  graffiti: rocket-pool

  ports:
    metrics: 5064


prysm:
  image:
    repository: gcr.io/prysmaticlabs/prysm/validator
    tag: stable
    pullPolicy: IfNotPresent

  verbosity: info
  network: pyrmont
  graffiti: rocket-pool

  ports:
    metrics: 8081

# Will create ServiceMonitor objects for Prometheus Operator
servicemonitor:
  enabled: false