apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rocketpool.fullname" . }}-config
data:
  config.yml: |
    rocketpool:
      storageAddress: {{ .Values.storageAddress }}
    smartnode:
      passwordPath: {{ .Values.datadir }}/password
      walletPath: {{ .Values.datadir }}/wallet
      validatorKeychainPath: {{ .Values.datadir }}/validators
    chains:
      eth1:
        provider: {{ .Values.eth1.provider }}
        client:
          options:
          - id: geth
            name: Geth
            image: ethereum/client-go:v1.9.20
            desc: made by the Ethereum Foundation
            link: https://geth.ethereum.org/
            params:
            - name: Ethstats Label
              env: ETHSTATS_LABEL
            - name: Ethstats Login
              env: ETHSTATS_LOGIN
          - id: infura
            name: Infura
            image: rocketpool/smartnode-pow-proxy:v0.0.3
            desc: uses Infura as a light client for ETH1
            link: https://infura.io/
            params:
            - name: Infura Project ID
              env: INFURA_PROJECT_ID
              regex: ^[0-9a-fA-F]{32}$
              required: true
      eth2:
        provider: {{ .Values.eth2.provider }}
        client:
          options:
          - id: lighthouse
            name: Lighthouse
            image: sigp/lighthouse:v0.2.12
            desc: made by Sigma Prime
            link: https://sigmaprime.io/
          - id: prysm
            name: Prysm
            beaconImage: gcr.io/prysmaticlabs/prysm/beacon-chain:HEAD-303edb-debug
            validatorImage: gcr.io/prysmaticlabs/prysm/validator:HEAD-303edb-debug
            desc: made by Prysmatic Labs
            link: https://prysmaticlabs.com/