apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rocketpool.fullname" . }}-settings
data:
  settings.yml: |
    chains:
      eth1:
        client:
          selected: {{ if .Values.proxy.enabled }}infura{{ else }}geth{{ end }}
{{- if .Values.proxy.enabled }}
          params:
          - env: INFURA_PROJECT_ID
            value: {{ .Values.eth1.infuraId }}
{{- end }}
      eth2:
        client:
          selected: {{ if .Values.eth2.lighthouse }}lighthouse{{ else }}prysm{{ end }}