{{- if and (eq .Values.eth2.lighthouse true) (eq .Values.servicemonitor.enabled true)}}

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "rocketpool.fullname" . }}-lighthouse
  labels:
    {{- include "rocketpool.labels" . | nindent 4 }}
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      smartnode: lighthouse
  endpoints:
  - path: /metrics
    port: metrics
  namespaceSelector:
    any: true

{{- end }}