{{- if and (eq .Values.eth2.prysm true) (eq .Values.eth2.lighthouse false) }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "rocketpool.fullname" . }}-prysm
  labels:
    smartnode: prysm
    {{- include "rocketpool.selectorLabels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      smartnode: prysm
      {{- include "rocketpool.selectorLabels" . | nindent 6 }}
  serviceName: {{ include "rocketpool.fullname" . }}
  replicas: 1
  template:
    metadata:
      labels:
        smartnode: prysm
        {{- include "rocketpool.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}-prysm
          image: "{{ .Values.prysm.image.repository }}:{{ .Values.prysm.image.tag }}"
          imagePullPolicy: {{ .Values.prysm.image.pullPolicy }}
          args:
            - --wallet-dir
            - {{ .Values.datadir }}/validators/prysm-non-hd
            - --wallet-password-file
            - {{ .Values.datadir }}/password
            - --beacon-rpc-provider
            - {{ .Values.eth2.provider }}
            - --monitoring-host
            - 0.0.0.0
            - --monitoring-port
            - {{ .Values.prysm.ports.metrics | quote }}
            - --verbosity
            - {{ .Values.prysm.verbosity }}
            - --graffiti
            - {{ .Values.prysm.graffiti }}
            - --accept-terms-of-use
            - --{{ .Values.eth2.network }}
          resources: 
{{ toYaml .Values.resources | indent 12 }}
          volumeMounts:
            - name: data
              mountPath: {{ .Values.datadir }}
          ports:
            - name: metrics
              containerPort: {{ .Values.prysm.ports.metrics }}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "rocketpool.fullname" . }}-data
{{- end }}
