apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "rocketpool.fullname" . }}-api
  labels:
    smartnode: api
    {{- include "rocketpool.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      smartnode: api
      {{- include "rocketpool.selectorLabels" . | nindent 6 }}
  serviceName: {{ include "rocketpool.fullname" . }}
  replicas: 1
  template:
    metadata:
      labels:
        smartnode: api
        {{- include "rocketpool.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}-api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          command: [ "/bin/sleep" ]
          args: [ "infinity" ]
          resources: 
{{ toYaml .Values.resources | indent 12 }}
          # livenessProbe:
          #   httpGet:
          #     path: /node/health
          #     port: {{ .Values.ports.metrics }}
          #   failureThreshold: 60
          #   initialDelaySeconds: 600
          #   periodSeconds: 60
          #   timeoutSeconds: 5
          # readinessProbe:
          #   httpGet:
          #     path: /node/health
          #     port: {{ .Values.ports.metrics }}
          #   failureThreshold: 3
          #   initialDelaySeconds: 60
          #   periodSeconds: 10
          #   timeoutSeconds: 5
          volumeMounts:
            - name: data
              mountPath: {{ .Values.datadir }}
            - name: config
              mountPath: {{ .Values.datadir }}/config.yml
              subPath: config.yml
            - name: settings
              mountPath: {{ .Values.datadir }}/settings.yml
              subPath: settings.yml
          ports:
            - name: metrics
              containerPort: {{ .Values.ports.metrics }}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "rocketpool.fullname" . }}-data
        - name: config
          configMap:
            name: {{ include "rocketpool.fullname" . }}-config
        - name: settings
          configMap:
            name: {{ include "rocketpool.fullname" . }}-settings
