apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "rocketpool.fullname" . }}-cli
  labels:
    smartnode: cli
    {{- include "rocketpool.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      smartnode: cli
      {{- include "rocketpool.selectorLabels" . | nindent 6 }}
  serviceName: {{ include "rocketpool.fullname" . }}
  replicas: 1
  template:
    metadata:
      labels:
        smartnode: cli
        {{- include "rocketpool.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}-cli
          image: "{{ .Values.cli.image.repository }}:{{ .Values.cli.image.tag }}"
          command: [ "/bin/bash", "-c", "--" ]
          args: [ "/bin/sleep infinity" ]
          resources: 
{{ toYaml .Values.cli.resources | indent 12 }}
          volumeMounts:
            - name: data
              mountPath: {{ .Values.datadir }}
            - name: config
              mountPath: {{ .Values.datadir }}/config.yml
              subPath: config.yml
            - name: settings
              mountPath: {{ .Values.datadir }}/settings.yml
              subPath: settings.yml
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "rocketpool.fullname" . }}-data
        - name: config
          configMap:
            name: {{ include "rocketpool.fullname" . }}-config
        - name: settings
          configMap:
            name: {{ include "rocketpool.fullname" . }}-settings
