{{- if and (eq .Values.eth2.prysm false) (eq .Values.eth2.lighthouse true) }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "rocketpool.fullname" . }}-lighthouse
  labels:
    smartnode: lighthouse
    {{- include "rocketpool.selectorLabels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      smartnode: lighthouse
      {{- include "rocketpool.selectorLabels" . | nindent 6 }}
  serviceName: {{ include "rocketpool.fullname" . }}
  replicas: 1
  template:
    metadata:
      labels:
        smartnode: lighthouse
        {{- include "rocketpool.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}-lighthouse
          image: "{{ .Values.lighthouse.image.repository }}:{{ .Values.lighthouse.image.tag }}"
          imagePullPolicy: {{ .Values.lighthouse.image.pullPolicy }}
          command:
            - lighthouse
            - validator
          args:
            - --datadir
            - {{ .Values.datadir }}/validators/lighthouse
            - --debug-level
            - {{ .Values.lighthouse.debugLevel }}
            - --testnet
            - {{ .Values.lighthouse.testnet }}
            - --beacon-node
            - {{ .Values.eth2.provider }}
            - --graffiti
            - {{ .Values.lighthouse.graffiti }}
            - --init-slashing-protection
            - --delete-lockfiles
          resources: 
{{ toYaml .Values.resources | indent 12 }}
          volumeMounts:
            - name: data
              mountPath: {{ .Values.datadir }}
          ports:
            - name: metrics
              containerPort: 5052
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "rocketpool.fullname" . }}-data
{{- end }}
