{{- if .Values.proxy.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "rocketpool.fullname" . }}-proxy
  labels:
    smartnode: proxy
    {{- include "rocketpool.labels" . | nindent 4 }}
spec:
  selector:
    smartnode: proxy
    {{- include "rocketpool.selectorLabels" . | nindent 4 }}
  ports:
    - name: proxy
      port: 8545
      protocol: TCP
{{- end }}
