{{- if and (eq .Values.eth2.prysm true) (eq .Values.eth2.lighthouse false)}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "rocketpool.fullname" . }}-prysm
  labels:
    {{- include "rocketpool.selectorLabels" . | nindent 4 }}
    smartnode: prysm
spec:
  selector:
    {{- include "rocketpool.selectorLabels" . | nindent 4 }}
    smartnode: prysm
  ports:
    - protocol: TCP
      port: {{ .Values.prysm.ports.metrics }}
      name: metrics
{{- end }}